config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :movies
  root 'movies#index'
  resources :movies do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :movie
  belongs_to :user
  validates_uniqueness_of :movie_id, scope: :user_id
end

app/models/movie.rb
class Movie < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :movies, dependent: :destroy
         has_many :likes, dependent: :destroy
  has_many :liked_movies, through: :likes, source: :movie
  has_many :comments, dependent: :destroy
  def already_liked?(movie)
    self.likes.exists?(movie_id: movie.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
            before_action :authenticate_user!
      
        def create
          movie = movie.find(params[:movie_id])
          comment = movie.comments.build(comment_params) #buildを使い、contentとmovie_idの二つを同時に代入
          comment.user_id = current_user.id
          if comment.save
            flash[:success] = "コメントしました"
            redirect_back(fallback_location: root_path) #直前のページにリダイレクト
          else
            flash[:success] = "コメントできませんでした"
            redirect_back(fallback_location: root_path) #直前のページにリダイレクト
          end
        end
      
        private
      
          def comment_params
            params.require(:comment).permit(:content)
          end
    
      
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(movie_id: params[:movie_id]) #user_idとmovie_idの二つを代入
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(movie_id: params[:movie_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    
        before_action :authenticate_user!, only: [:new, :create]
        def index
          if params[:search] != nil && params[:search] != ''
            search = params[:search]
            @movies = Movie.where("name LIKE ? OR directorsname LIKE ?", "%#{search}%", "%#{search}%")
          else
            @movies = Movie.all.page(params[:page]).per(5)

          end
        end
      
        def new
          @movie = Movie.new
        end
      
        def create
          movie = Movie.new(movie_params)
          movie.user_id=current_user.id
          if movie.save
            redirect_to :action => "index"
          else
            redirect_to :action => "new"
          end
        end
      
        def show
          @movie = Movie.find(params[:id])
          @comments = @movie.comments
          @comment = Comment.new
        end
      
        def edit
          @movie = Movie.find(params[:id])
        end
      
        def update
          movie = Movie.find(params[:id])
          if movie.update(movie_params)
            redirect_to :action => "show", :id => movie.id
          else
            redirect_to :action => "new"
          end
        end
      
        # 追加ここから
        def destroy
          movie = Movie.find(params[:id])
          movie.destroy
          redirect_to action: :index
        end
        # ここまで
      
        private
        def movie_params
          params.require(:movie).permit(:name, :genre, :day, :directorsname, :review, :degree)
        end
      
      
      
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
    def getPercent(number) 
        if number.present?
          calPercent = number/5.to_f * 100
          # calPercent = number/10.to_f * 100
          #↑１０段階評価の際は2行目コメントアウトを外して、1行目をコメントアウト。
          percent = calPercent.round
          #↑CSSは小数が含まれると、widthの幅を指定できないので四捨五入して整数化。
          return percent.to_s
        else
          return 0
        end
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Radical</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/38ca4c3da0.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>
 <header>
  <h1>Radical scenes in movies</h1>
  <div class="header-list">
   <ul>
    <% if user_signed_in? %>
     <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
    <% else %>
     <li><%= link_to "新規登録", new_user_registration_path %></li>
     <li><%= link_to "ログイン", new_user_session_path %></li>
    <% end %>
   </ul>
  </div>
 </header>
 <main>
  <%= yield %>
 </main>
</body>

</html>

app/views/movies/edit.html.erb
<%= form_for @movie do |f| %>
    <div class="field">
    <%= f.label :映画名 %>
    <%= f.text_field :name, :size => 30 %>
  </div>

<div class="field">
<%= f.label :ジャンル %>
<%= f.text_field :genre, :size => 30 %>
</div>

<div class="field">
<%= f.label :公開日 %>
<%= f.text_field :day, :size => 30 %>
</div>

<div class="field">
<%= f.label :監督名 %>
<%= f.text_field :directorsname, :size => 30 %>
</div>

<div class="field">
<%= f.label :画像 %>
<%= f.file_field :image %>
</div>

<div class="field">
    <%= f.label :レビュー  %>
    <%= f.text_area :review, :size => "30x4" %>
  </div>

    <%= f.submit "編集する" %>
  <% end %>
  

app/views/movies/index.html.erb
<h1>自分の題名</h1>
<h3>一覧ページ</h3>
<h3>投稿を検索</h3>
 <%= form_tag({controller:"movies",action:"index"}, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag '検索する'  %>
<% end %>
<%= link_to "新規投稿へ", new_movie_path %>
<%= page_entries_info @movies %>
<div class="movies-container">
  <% @movies.each do |t| %>
    <div class="movie">
      <%= t.user.email %>
      <%= t.name %>
      <div>
<h2>総合評価：
<span class="star-rating">
   <span class="star-rating-front" style="width: <%= getPercent(t.degree) %>%;">★★★★★</span>
   <span class="star-rating-back">★★★★★</span>
</span> 
</h2>
</div>
      <%= t.genre %>
      <%= t.day %>
      <%= t.directorsname %>
      <% if user_signed_in? %>
      <% if current_user.already_liked?(t) %>
          <%= button_to movie_like_path(id: t.id, movie_id: t.id), method: :delete do %>
            <i class="fas fa-heart"></i><%= t.likes.count %>
            <% end %>

      <% else %>
          <%= button_to movie_likes_path(id: t.id, movie_id: t.id), method: :post do %>
            <i class="fa-regular fa-heart"></i><%= t.likes.count %>
          <% end %>
      <% end %>

  <% else %>
      <p>いいねの数 = </p><%= t.likes.count %>
  <% end %>
      <%= link_to "詳細へ", movie_path(t.id) %>
      <%= link_to "編集する", edit_movie_path(t.id) %>
      <%= button_to "削除する", movie_path(t.id), method: :delete %> 
      </div>
  <% end %>
</div>
<%= paginate @movies %>


app/views/movies/new.html.erb
<h1>(自分の題名)</h1>
<h3>新規投稿ページ</h3>
<%= form_for @movie do |f| %>


  <div class="field">
    <%= f.label :映画名 %>
    <%= f.text_field :name, :size => 30 %>
  </div>

  <h5>総合評価</h5>
  <div class="post_form">
   <%= f.radio_button :degree, 5 ,id: 'star1'%>
   <label for="star1"><span class="text">超過激</span>★</label>

   <%= f.radio_button :degree, 4 ,id: 'star2'%>
   <label for="star2"><span class="text">めっちゃ過激</span>★</label>

   <%= f.radio_button :degree, 3 ,id: 'star3'%>
   <label for="star3"><span class="text">過激</span>★</label>

   <%= f.radio_button :degree, 2 ,id: 'star4'%>
   <label for="star4"><span class="text">やや過激</span>★</label>

   <%= f.radio_button :degree, 1 ,id: 'star5'%>
   <label for="star5"><span class="text">ちょっと過激</span>★</label>
</div>

<div class="field">
<%= f.label :ジャンル %>
<%= f.text_field :genre, :size => 30 %>
</div>


<div class="field">
<%= f.label :公開日 %>
<%= f.text_field :day, :size => 30 %>
</div>


<div class="field">
<%= f.label :監督名 %>
<%= f.text_field :directorsname, :size => 30 %>
</div>


<div class="field">
<%= f.label :画像 %>
<%= f.file_field :image %>
</div>

<div class="field">
    <%= f.label :レビュー  %>
    <%= f.text_area :review, :size => "30x4" %>
  </div>

  <%= f.submit "投稿する" %>
<% end %>

<%= link_to "一覧に戻る", movies_path %>

app/views/movies/show.html.erb
<h1>Detail</h1>
<h3>詳細</h3>
<div class="movie">
  <p><%= @movie.name %></p>
  <p><%= @movie.genre %></p>
  <p><%= @movie.day %></p>
  <p><%= @movie.directorsname %></p>
  <p><%= @movie.image %></p>
  <p><%= @movie.review %></p>
  <p><%= @movie.created_at %></p>
  <% if user_signed_in? %>
      <% if current_user.already_liked?(@movie) %>
        <%= button_to movie_like_path(@movie), method: :delete do %>
          <i class="fas fa-heart"></i><%= @movie.likes.count %>
        <% end %>

      <% else %>
        <%= button_to movie_likes_path(@movie), method: :post do %>
          <i class="fa-regular fa-heart"></i><%= @movie.likes.count %>
           <% end %> 
             
      <% end %>
    <% else %>
      <p>いいねの数 = </p><%= @movie.likes.count %>
    <% end %>
  <%= link_to "編集する", edit_movie_path(@movie.id) %>
</div>

<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@movie, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>
  
<%= link_to "一覧に戻る", movies_path %>


app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>